skip_commits:
  files:
    - '**/*.md'
    - '.vscode/**/*'
    - '.github/**/*'
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> .appveyor.yml, test\bin\*.ps1'
  - C:\projects\helpers -> .appveyor.yml, test\bin\*.ps1
matrix:
  fast_finish: true
build: 'off'
image: Visual Studio 2019
environment:
  SCOOP: C:\projects\scoop
  SCOOP_HOME: C:\projects\scoop\apps\scoop\current
  SCOOP_HELPERS: C:\projects\helpers
  LESSMSI: '%scoop_helpers%\lessmsi\lessmsi.exe'
  INNOUNP: '%scoop_helpers%\innounp\innounp.exe'
  matrix:
    - PowerShell: 5
#     - PowerShell: 6
init:
  - ps: |
      (Get-PSProvider 'FileSystem').Home = 'C:\projects\'
      if(!(Test-Path "$env:SCOOP_HOME")) {
        git clone -q --depth=1 -b v0.3.0 'https://github.com/lukesampson/scoop' "$env:SCOOP_HOME"
        git clone -q --depth=1 'https://github.com/ScoopInstaller/Main' "$env:SCOOP\buckets\main"
      }
for:
  - matrix:
      only:
        - PowerShell: 5
    install:
      - ps: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - ps: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
#   - matrix:
#       only:
#         - PowerShell: 6
#     install:
#       - pwsh: . "$env:SCOOP_HOME\test\bin\init.ps1"
#     test_script:
#       - pwsh: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
on_finish:
  - ps: |
      $log = 'Install.log'
      if (Test-Path $log) {
        Get-Content $log -Raw | Write-Host
        Push-AppveyorArtifact $log
      }
