skip_commits:
  files:
    - '**/*.md'
cache:
  - '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> appveyor.yml'
  - 'C:\projects\helpers'
  - '%SCOOP%\apps'
matrix:
  fast_finish: true
build: 'off'
image: Visual Studio 2019
clone_folder: '%SCOOP%\buckets\ox'
environment:
  SCOOP: C:\SCOOP
  SCOOP_HOME: '%SCOOP%\apps\scoop\current'
  matrix:
    - PowerShell: 5
    - PowerShell: 6
    - PowerShell: 7
init:
  - ps: |
      (Get-PSProvider 'FileSystem').Home = 'C:\projects\'
      if(!(Test-Path "$env:SCOOP_HOME")) {
        git clone -q --depth=1 --branch 'NEW' 'https://github.com/Ash258/Scoop-Core' "$env:SCOOP_HOME"
        git clone -q --depth=1 'https://github.com/ScoopInstaller/Main' "$env:SCOOP\buckets\main"
      }
for:
  - matrix:
      only:
        - PowerShell: 5
        - PowerShell: 6
        - PowerShell: 7
    install:
      - ps: . "$env:SCOOP_HOME\test\bin\init.ps1"
    test_script:
      - ps: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
on_finish:
  - ps: |
      $log = 'Install.log'
      if (Test-Path $log) {
        Get-Content $log -Raw | Write-Host
        Push-AppveyorArtifact $log
      }
